### ISSUE TITLE
[아이템 10] equals는 일반 규약을 지켜 재정의하라

### ISSUE THREAD

**Issue by Jeongminyooa** [Yooa-Backend-Study/effective-java-book#16]

**Comment by Jeongminyooa** [comment]
Q. AutoValue 프레임워크의 단점이나 side effect가 뭐가 있을지? 

A. 애너테이션으로 재정의하는 방법이 별로 좋은 것 같진 않다. lombok에도 @EqualsAndHashcode 가 있는데 이를 직접 사용하는 건 본 적이 없는 것 같다. 보통 오버라이딩을 해서 사용하고, ide에서 자동 생성해주는 기능을 활용해 수정해나가는 편.

@EqualsAndHashcode 테스트 코드를 작성해 본 경험이 있는데, 객체 필드 값만 일치하면 hashCode는 true가 나오고, equals에서는 false 가 나오더라. 이런 세부적인 로직을 정확히 파악하고 있지 않다면 오히려 알고 있는 지식에 혼란을 더하는 것 같다 느낌. 본인이 러닝 커브가 부담 없다면 잘 알아보고 적용하는건 좋지만, 대부분 그렇지 못한 상황이 크니 재정의가 더 안전하고 빠르게 적용 가능할 듯.

**Comment by Jeongminyooa** [comment]
61페이지 두번째 단락

> … 예컨대 java.net.URL의 equals는 주어진 URL과 매핑돈 호스트의 IP 주소를 이용해 비교한다. 호스트 이름을 IP주소로 바꾸려면 네트워크를 통해야 하는데, 그 결과가 항상 같다고 보장할 수 없다. 이는 URL의 equals가 일잔 규약을 어기게 하고, 실무에서도 종종 문제를 일으킨다…
> 

이 부분이 이해가 안간다.

**Comment by juu924** [comment]
> 61페이지 두번째 단락
> 
> > … 예컨대 java.net.URL의 equals는 주어진 URL과 매핑돈 호스트의 IP 주소를 이용해 비교한다. 호스트 이름을 IP주소로 바꾸려면 네트워크를 통해야 하는데, 그 결과가 항상 같다고 보장할 수 없다. 이는 URL의 equals가 일잔 규약을 어기게 하고, 실무에서도 종종 문제를 일으킨다…
> 
> 이 부분이 이해가 안간다.

제가 생각하기에는  한 도메인 당 dns 가 여러 대 일 수도 있으니, 같은 도메인이라고 해서 같은 IP 주소를 반환한다는 보장이 없기 때문에 일반 규약을 어기게 된다 인 것 같습니다. 프로토콜이나 호스트, 포트 번호가 같아서 같은 URL 이 맞음에도 DNS 서버 주소 때문에 false 를 반환하는 경우를 말하는 것 같아요.

해당 링크의 3.3. Opening a Remote Connection 부분 한 번 읽어보시면 비슷한 내용이 적혀 있습니다!
https://www.baeldung.com/java-url-vs-uri

**Comment by Jeongminyooa** [comment]
dns 동작 원리를 몰라서 이해하지 못했던 것 같습니다. 호스트는 항상 같은 IP 주소를 반환하지 않는 부분이 이해되니 왜 equals가 항상 같은 결과를 보장하지 않는지도 이해되네요..!

좋은 답변 감사합니다👍
