### ISSUE TITLE
[아이템 14] Comparable을 구현할지 고려하라

### ISSUE THREAD

**Issue by Jeongminyooa** [Yooa-Backend-Study/effective-java-book#20]

**Comment by Jeongminyooa** [comment]
Q. 92p 코드 14-3 메서드 연쇄 방식의 성능 저하 이유가 궁금하다.

A. 람다는 메인 스레드에서 동작하지 않고, 별도의 스레드를 할당 받아 동작하니 스레드를 잡아먹는 듯. 또 가변 인수 사용이 안되어서 final로만 선언해주어야 한다는 점에서 성능 저하가 되지 않을까 싶음.

꼬리 Q. 메인 스레드와 별도 스레드에서 동작하면 성능이 더 좋아져야 하는 것 아닌가?

꼬리 A. 좋아질 순 있지만 스레드 풀 개념에서 데이터가 너무 많아지거나 정렬같은 작업을 해야 한다면 스레드를 많이 차지하게 될 것. 그 과정에서 다른 작업을 못하게 되니 그런 상황을 말한 것 같다.

그런데 보통은 그렇게 크게 데이터를 활용할 일이 없으니 람다와 연쇄 메서드 방식의 성능 차이가 클 것 같지 않다는 의견. 컴페어러블을 보통 구현할 일이 거의 없기 때문.

구현하면 좋지만, 상황에 따라 다르게 정렬해야하는 경우가 다수이기에 굳이 사용하지 않음. (코테 대비에는 좋음.)

**Comment by lorlorv** [comment]
Q. 89p 2번째 단락 1~4 줄
> 이상의 세 규약은 compareTo	 메서드로 수행하는 동치성 검사도 eqauls 규약과 똑같이 반사성, 대칭성, 추이성을 충족해야 함을 뜻한다. 그래서 주의사항도 똑같다. 기존 클래스를 확장한 구체 클래스에서 새로운 값 컴포넌트를 추가했다면 compareTo 규약을 지킬 방법이 없다.

위 문장을 검증해보고자 아래와 같은 테스트 코드를 짜보았을 때, 결과는 equal 규약만 위배한 것이지 compareTo 규약은 위배하지 않았다고 생각한다. (구체 클래스에서 새로운 값 컴포넌트를 추가해도 비교 결과는 올바르게 출력되기 때문) 그렇다면 왜 '기존 클래스를 확장한 구체 클래스에서 새로운 값 컴포넌트를 추가했다면 compareTo 규약을 지킬 방법이 없다고 말하는가 ?

```
package item14;

public class Point implements Comparable<Point> {
    int x;
    int y;

    public Point(int x, int y) {
        this.x = x;
        this.y = y;
    }

    @Override
    public int compareTo(Point other) {
        // 거리를 기준으로 비교
        double thisDistance = Math.sqrt(x * x + y * y);
        double otherDistance = Math.sqrt(other.x * other.x + other.y * other.y);

        return Double.compare(thisDistance, otherDistance);
    }
}

```

```
package item14;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class ColoredPoint extends Point {
    private String color;

    public ColoredPoint(int x, int y, String color) {
        super(x, y);
        this.color = color;
    }

    @Override
    public int compareTo(Point other) {
        // 먼저 상위 클래스(Point)의 compareTo를 호출하여 기존 비교를 수행
        int superComparison = super.compareTo(other);

        // 새로운 값 컴포넌트(color)를 고려하여 추가 비교
        if (superComparison != 0) {
            return superComparison; // 상위 비교 결과가 0이 아니면 반환
        }

        // color 기준으로 추가 비교
        return String.CASE_INSENSITIVE_ORDER.compare(this.color, ((ColoredPoint) other).color);
    }

    @Override
    public String toString() {
        return "ColoredPoint{" +
                "color='" + color + '\'' +
                ", x=" + x +
                ", y=" + y +
                '}';
    }

    public static void main(String[] args) {
        ColoredPoint a = new ColoredPoint(1, 2, "a");
        ColoredPoint b = new ColoredPoint(2, 1, "b");

        List<ColoredPoint> list = new ArrayList<>();
        list.add(a);
        list.add(b);

        System.out.println("list1 : " + a.compareTo(b));

        Collections.sort(list);
        System.out.println(list);

        List<ColoredPoint> list2 = new ArrayList<>();
        list2.add(b);
        list2.add(a);

        System.out.println("list2 : " + b.compareTo(a));
        Collections.sort(list2);
        System.out.println(list2);

    }
}
```

A. 말 그대로 구체 클래스에서 compareTo 메서드를 재정의하지 않았을 경우에compareTo 규약을 지킬 수 없다고 하는 뜻인 것 같다.

다른 분들은 어떻게 이해하셨는지 궁금하다.

**Comment by lorlorv** [comment]
> Q. 92p 코드 14-3 메서드 연쇄 방식의 성능 저하 이유가 궁금하다.
> 
> A. 람다는 메인 스레드에서 동작하지 않고, 별도의 스레드를 할당 받아 동작하니 스레드를 잡아먹는 듯. 또 가변 인수 사용이 안되어서 final로만 선언해주어야 한다는 점에서 성능 저하가 되지 않을까 싶음.
> 
> 꼬리 Q. 메인 스레드와 별도 스레드에서 동작하면 성능이 더 좋아져야 하는 것 아닌가?
> 
> 꼬리 A. 좋아질 순 있지만 스레드 풀 개념에서 데이터가 너무 많아지거나 정렬같은 작업을 해야 한다면 스레드를 많이 차지하게 될 것. 그 과정에서 다른 작업을 못하게 되니 그런 상황을 말한 것 같다.
> 
> 그런데 보통은 그렇게 크게 데이터를 활용할 일이 없으니 람다와 연쇄 메서드 방식의 성능 차이가 클 것 같지 않다는 의견. 컴페어러블을 보통 구현할 일이 거의 없기 때문.
> 
> 구현하면 좋지만, 상황에 따라 다르게 정렬해야하는 경우가 다수이기에 굳이 사용하지 않음. (코테 대비에는 좋음.)

@skehdxhd96 
동민님께서 람다식에 대한 성능저하에 대한 이유를 말씀해주셨는데, 
이번 발표 주제에 대해 공부하면서 찾아보니까 제가 이해한 바와 다른 점이 있어 다시 질문드립니다 !

람다 표현식은 함수형 인터페이스 (추상 메소드를 하나만 가지는)를 구현하는 익명 클래스의 인스턴스로 컴파일되어 람다 표현식을 사용할 때마다 이러한 익명 클래스의 인스턴스가 생성됩니다. 즉, 람다 표현식을 사용할 때마다 새로운 객체가 생성되므로 메모리 할당 및 객체 생성 오버헤드가 발생할 수 있기 때문에  성능 저하의 원인이 될 수 있다고 이해했습니다. 

그래서 람다식은 별도의 스레드에서 동작한다는 것과 직접적인 관련이 없고, 객체 생성에 대한 오버헤드가 성능 저하의 주 원인이라고 생각합니다.

혹시 제가 잘못 이해한건 지 다른 분들도 천천히 확인해보시고 의견 부탁드립니다!

https://tourspace.tistory.com/12

**Comment by Jeongminyooa** [comment]
a

**Comment by Jeongminyooa** [comment]
@lorlorv  
> 아래와 같은 테스트 코드를 짜보았을 때, 결과는 equal 규약만 위배한 것이지 compareTo 규약은 위배하지 않았다고 생각한다. (구체 클래스에서 새로운 값 컴포넌트를 추가해도 비교 결과는 올바르게 출력되기 때문) 그렇다면 왜 '기존 클래스를 확장한 구체 클래스에서 새로운 값 컴포넌트를 추가했다면 compareTo 규약을 지킬 방법이 없다고 말하는가 ?

Point 객체와 ColoredPoint 객체는 상속 관계이기 때문에 아래와 같은 코드가 성립됩니다.
```java
    @Test
    public void compareTo_일반_규약_테스트() {
        Point a = new Point(1, 2);
        ColoredPoint b = new ColoredPoint(2, 1, "b");

        System.out.println(a.compareTo(b));
        System.out.println(b.compareTo(a));
    }
```
제안하신 코드로 돌려보면 Point의 compareTo는 색상을 무시한 채 비교하고, ColoredPoint의 equals는 입력 매개변수의 클래스 종류가 Point이므로 ClassCastException이 발생하네요.  (대칭성 위반)

만약, ColoredPoint.compareTo가 Point와 비교할 때는 색상을 무시하도록 해결해볼 수 있겠으나
```java
@Override public int compareTo(Point other) {
		if(!(other instanceof Point))
				return false;

		if(!(o instanceof ColoredPoint))
				return other.equals(this);

		return super.compareTo(other) && String.CASE_INSENSITIVE_ORDER.compare(this.color, ((ColoredPoint) other).color);
}
```
아래와 같이 추이성이 위반될 수 있습니다.
(a와 b는 같고, b와 c도 같은데 a와 c는 다른 결과)
```java
    @Test
    public void compareTo_일반_규약_테스트() {
        ColoredPoint a = new ColoredPoint(2, 1, "a");
        Point b = new Point(1, 2);
        ColoredPoint c = new ColoredPoint(2, 1, "c");
    }
```
이런 측면에서 객체 지향적 추상화의 이점을 포기하지 않는 한 규약을 지킬 수 없다고 하는 것 같네요.
