### ISSUE TITLE
[아이템 34] int 상수 대신 열거 타입을 사용하라

### ISSUE THREAD

**Issue by Jeongminyooa** [Yooa-Backend-Study/effective-java-book#50]

**Comment by Jeongminyooa** [comment]
Q. valueOf와 fromString 재정의에 관한 내용, valueOf를 재정의하면 안되는건가?

**Comment by lorlorv** [comment]
@Jeongminyooa 

이미 Enum 클래스 내부에 '주어진 문자열로 Enum 상수를 찾는다' 라는 정확한 로직을 가지고 있기 때문에 만약 valueOf 메서드를 재정의하면 Enum 클래스의 기본 동작을 변경하는 것이고 이는 일반적인 사용 방법과 어긋나게 됩니다. 다른 개발자들도 이 Enum 클래스를 사용할 때 'valueOf()'의 메서드의 일반적인 동작을 예측하고 의존하게되는데 이 메서드를 재정의해 버린다면 다른 개발자와의 코드 호환성 문제가 발생할 수도 있으니 valueOf를 재정의하지 말고, fromString과 같은 메서드를 따로 정의하여 사용하는 것이 좋은 방향이라고 합니다 !

이 안건에 대해 찾아보니, 오늘 스터디 시간에 같이 토의하면서 도출된 결론과 상당히 유사하여 약간의 부가설명과 같이 나눴던 내용 정리로 답변 마무리 하겠습니다 😊

https://biosidmartin.com/can-you-override-enum-valueof/
